[package]
name = "quickjs-parse"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
quickjs-wasm-sys = { git = "https://github.com/Shopify/javy", branch = "main" }
once_cell = "1.8.0"

[profile.release]
lto = true
opt-level = 3

[workspace]
