[package]
name = "quickjs-wasm-rs"
version = "0.1.0"
authors = ["Saúl Cabrera <saulecabrera@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
quickjs-wasm-sys = { path = "../quickjs-wasm-sys" }
rmp-serde = "^0.15"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-transcode = "1.1"
convert_case = "0.4"

[dev-dependencies]
quickcheck = "1"

[features]
messagepack = []
