[package]
name = "javy-core"
version = "0.1.0"
authors = ["Saúl Cabrera <saulecabrera@gmail.com>"]
edition = "2018"

[[bin]]
name = "javy_core"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
quickjs-wasm-rs = { path = "../quickjs-wasm-rs", features = ["messagepack"] }
serde-transcode = "1.1"
rmp-serde = "^0.15"
wee_alloc = "0.4.5"
serde_json = { version = "1", optional = true }
once_cell = "1.4.0"

[features]
json-io = ["serde_json"]
